matrix:
  include:
    - language: go
      go:
        - "1.11"
        - "1.12"

    - language: node_js
      node_js:
        - "10"
        - "12"
      install:
          - npm i
      env:
          - NODE_ENV=prod
      script:
          - npm run lint
          - npm run build
